//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Com;
    
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<DailyVOD> DailyVODs { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MovementTraining> MovementTrainings { get; set; }
        public virtual DbSet<MovementTrainingDetail> MovementTrainingDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseZarinpalLog> PurchaseZarinpalLogs { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBasket> UserBaskets { get; set; }
        public virtual DbSet<UserBought> UserBoughts { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserShipping> UserShippings { get; set; }
        public virtual DbSet<UserVOD> UserVODs { get; set; }
        public virtual DbSet<DiscountCode> DiscountCodes { get; set; }
    }
}
