//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int CID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string id { get; set; }
    }
}
