//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyVOD
    {
        public int DVID { get; set; }
        public System.DateTime Date { get; set; }
        public int VID { get; set; }
        public string VODName { get; set; }
    }
}
