//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementTrainingDetail
    {
        public int MTDID { get; set; }
        public int MTID { get; set; }
        public string ImgName { get; set; }
        public string ContextDetail { get; set; }
    }
}
