//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementTraining
    {
        public int MTID { get; set; }
        public string Context { get; set; }
        public string VideoAddress { get; set; }
        public string Part { get; set; }
        public string SubPart { get; set; }
        public string Movement { get; set; }
        public string Filter { get; set; }
    }
}
