//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PID { get; set; }
        public int CatID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string specifications { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public string Img { get; set; }
        public bool Available { get; set; }
        public double Rate { get; set; }
    }
}
