//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int SID { get; set; }
        public int CatID { get; set; }
        public string CatName { get; set; }
        public int SequenceNum { get; set; }
        public bool IsBanner { get; set; }
    }
}
