//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShipping
    {
        public int USHID { get; set; }
        public int UID { get; set; }
        public string ProductsID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> SendingTime { get; set; }
        public double Cost { get; set; }
        public bool IsPaid { get; set; }
        public string DiscountCode { get; set; }
    }
}
