//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UID { get; set; }
        public string TellNumber { get; set; }
        public string Email { get; set; }
        public string DeviceID { get; set; }
        public string FBToken { get; set; }
        public string ActiveCode { get; set; }
        public int Credit { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public int RewardState { get; set; }
        public bool Active { get; set; }
        public string SecretKey { get; set; }
        public string AppVersion { get; set; }
        public string APIVersion { get; set; }
        public string DeviceModel { get; set; }
        public Nullable<int> Access { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public string NickName { get; set; }
        public string CodeMeli { get; set; }
        public string Address { get; set; }
        public string CodePosti { get; set; }
        public string City { get; set; }
        public string Ostan { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Birthdat { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> ScreenMode { get; set; }
        public Nullable<double> RCBackSquat { get; set; }
        public Nullable<double> RCPullUp { get; set; }
        public Nullable<double> RCRun { get; set; }
    }
}
