//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int UMID { get; set; }
        public string Context { get; set; }
        public bool Seen { get; set; }
        public int UID { get; set; }
    }
}
