//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOD
    {
        public int VID { get; set; }
        public string Name { get; set; }
        public System.DateTime Moment { get; set; }
        public string DesignerName { get; set; }
        public int DesignerUID { get; set; }
        public string Info { get; set; }
        public string Round { get; set; }
        public string Movment { get; set; }
        public bool IsPreMade { get; set; }
    }
}
