//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com
{
    using System;
    using System.Collections.Generic;
    
    public partial class VODMovment
    {
        public int VMID { get; set; }
        public int VID { get; set; }
        public int MID { get; set; }
        public string Extra { get; set; }
    
        public virtual MovementTraining MovementTraining { get; set; }
        public virtual VOD VOD { get; set; }
    }
}
